version: '3.3'
services:
  api-github:
    image: joaoroberto/api-github
    restart: always
    build: ./
    working_dir: /api-github
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "80:80"
    command: mvn spring-boot:run