spring:
  application:
    title: api-github
    version: 2023.01
  mustache:
    check-template-location: false

server:
  port: 80

logging:
  level:
    root: info
    pt:
      com:
        cocus:
          apigithub:
            service: debug

api-github:
  url: https://api.github.com
