spring:
  application:
    title: api-github
    version: 2023.01

server:
  port: 8080

logging:
  level:
    root: info
    pt:
      com:
        cocus:
          adapter: info

api-github:
  url: https://api.github.com

spring-doc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    enabled: true
    path: swagger/index.html
