spring:
  application:
    title: api-github
    version: 2023.01

server:
  port: 8080
  servlet:
    context-path: /api/github/v1

logging:
  level:
    root: info
    pt:
      com:
        cocus:
          adapter: info

api-github:
  url: https://api.github.com

