name: Continuous Integration with GitHub Actions

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application Jar
      working-directory: ./
      run: mvn clean package -DskipTests -f pom.xml
      
    - name: Docker Compose Build
      working-directory: ./
      run: docker compose build

    - name: Tag and push image to Amazon ECR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-github:latest ${{ secrets.ECR_IMAGE_REPO_URL }}:${{github.run_id}}
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-github:latest ${{ secrets.ECR_IMAGE_REPO_URL }}:latest

        docker push ${{ secrets.ECR_IMAGE_REPO_URL }}:${{github.run_id}}
        docker push ${{ secrets.ECR_IMAGE_REPO_URL }}:latest

    - name: Push to Docker Hub Container registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/api-github:latest ${{ secrets.DOCKER_USERNAME }}/api-github:${{github.run_id}}

        docker push ${{ secrets.DOCKER_USERNAME }}/api-github:${{github.run_id}}
        docker push ${{ secrets.DOCKER_USERNAME }}/api-github:latest
